import Head from "next/head";
import styles from "../styles/Home.module.css";
import SidebarComponent from './../components/Sidebar/index';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex gap-2">
        <SidebarComponent />
        <p className="text-2xl">Dashboard</p>
      </div>
          </div>
  );
}
